Repository ctrl-hub/sdk.ts, pull requests merged in 2025-03, with the labels that each got.

#42 Update group model and service
  dist/index.js
  dist/models/Group.d.ts
  dist/models/Group.js
  dist/services/GroupService.d.ts
  dist/services/GroupService.js
  package-lock.json
  package.json
  src/models/Group.ts
  src/services/GroupService.ts
Labels: improvement

#43 remove appointment type
  dist/index.js
  dist/models/Appointment.d.ts
  dist/models/Appointment.js
  package.json
  src/models/Appointment.ts
Labels: improvement

#46 Add assignees to operations
  dist/index.js
  dist/models/Operation.js
  package.json
  src/models/Operation.ts
Labels: new thing

#49 Add operation template export
  dist/index.d.ts
  dist/index.js
  package.json
  src/index.ts
Labels: klto

#51 add team member and operation assignee patching
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/services/OperationsService.d.ts
  dist/services/OperationsService.js
  dist/services/TeamsService.d.ts
  dist/services/TeamsService.js
  package.json
  src/Client.ts
  src/services/OperationsService.ts
  src/services/TeamsService.ts
Labels: new thing

#54 Allow patching of vehicle assignee
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/services/VehiclesService.d.ts
  dist/services/VehiclesService.js
  dist/utils/JsonSerializer.d.ts
  dist/utils/JsonSerializer.js
  package.json
  src/Client.ts
  src/services/VehiclesService.ts
  src/utils/JsonSerializer.ts
Labels: new thing

#53 Added patch for vehicle equipment
  dist/index.js
  dist/services/VehiclesService.d.ts
  dist/services/VehiclesService.js
  package.json
  src/services/VehiclesService.ts
Labels: new thing

#56 update scheme and work order dates
  dist/index.js
  dist/models/Scheme.d.ts
  dist/models/Scheme.js
  dist/models/WorkOrder.d.ts
  dist/models/WorkOrder.js
  package.json
  src/models/Scheme.ts
  src/models/WorkOrder.ts
Labels: improvement

#57 add operation team patching
  dist/index.js
  dist/models/Operation.js
  dist/services/OperationsService.d.ts
  dist/services/OperationsService.js
  package.json
  src/models/Operation.ts
  src/services/OperationsService.ts
Labels: new thing

#58 Add vehicle team patching
  dist/index.js
  dist/models/Vehicle.js
  dist/services/VehiclesService.d.ts
  dist/services/VehiclesService.js
  package.json
  src/models/Vehicle.ts
  src/services/VehiclesService.ts
Labels: new thing

#59 Fix sort direction ts
  dist/index.js
  dist/utils/RequestBuilder.d.ts
  dist/utils/RequestBuilder.js
  dist/utils/RequestOptions.d.ts
  package.json
  src/utils/RequestBuilder.ts
  src/utils/RequestOptions.ts
Labels: klto

#60 Add operation template requirements
  dist/index.js
  dist/models/OperationTemplate.d.ts
  dist/models/OperationTemplate.js
  package.json
  src/models/OperationTemplate.ts
  src/utils/JsonSerializer.ts
Labels: new thing

#62 add template to operation
  dist/index.js
  dist/models/Operation.js
  package.json
  src/models/Operation.ts
Labels: improvement

#61 Added getExposures function
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/services/BaseService.d.ts
  dist/services/EquipmentExposureService.d.ts
  dist/services/EquipmentExposureService.js
  dist/utils/Requests.js
  src/Client.ts
  src/models/EquipmentExposure.ts
  src/services/EquipmentExposureService.ts
Labels: new thing

#63 bumped version to 0.1.138
  package.json
Labels: klto

#64 add scheme and work order templates
  dist/Client.d.ts
  dist/Client.js
  dist/index.d.ts
  dist/index.js
  dist/models/SchemeTemplate.d.ts
  dist/models/SchemeTemplate.js
  dist/models/WorkOrderTemplate.d.ts
  dist/models/WorkOrderTemplate.js
  dist/services/SchemeTemplatesService.d.ts
  dist/services/SchemeTemplatesService.js
  dist/services/WorkOrderTemplatesService.d.ts
  dist/services/WorkOrderTemplatesService.js
  dist/utils/Hydrator.js
  package.json
  src/Client.ts
  src/index.ts
  src/models/SchemeTemplate.ts
  src/models/WorkOrderTemplate.ts
  src/services/SchemeTemplatesService.ts
  src/services/WorkOrderTemplatesService.ts
  src/utils/Hydrator.ts
Labels: new thing

#66 add template to schemes and work order models
  dist/Client.js
  dist/index.js
  dist/models/EquipmentExposure.js
  dist/models/Scheme.js
  dist/models/WorkOrder.js
  dist/services/BaseService.d.ts
  dist/utils/Requests.js
  package.json
  src/models/Scheme.ts
  src/models/WorkOrder.ts
Labels: new thing

#65 Add stats to BaseService
  dist/Client.js
  dist/index.js
  dist/models/OrganisationMemberStats.d.ts
  dist/models/OrganisationMemberStats.js
  dist/services/BaseService.d.ts
  dist/services/BaseService.js
  dist/services/OrganisationMembersService.d.ts
  dist/services/OrganisationMembersService.js
  dist/utils/Hydrator.js
  package.json
  src/Client.ts
  src/models/OrganisationMemberStats.ts
  src/services/BaseService.ts
  src/services/OrganisationMembersService.ts
  src/utils/Hydrator.ts
Labels: new thing
