Repository ctrl-hub/sdk.ts, pull requests merged in 2025-02, with the labels that each got.

#24 add operation templates
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/models/Label.d.ts
  dist/models/Label.js
  dist/models/OperationTemplate.d.ts
  dist/models/OperationTemplate.js
  dist/services/OperationTemplatesService.d.ts
  dist/services/OperationTemplatesService.js
  dist/utils/Hydrator.js
  package.json
  src/Client.ts
  src/models/Label.ts
  src/models/OperationTemplate.ts
  src/models/Scheme.ts
  src/services/OperationTemplatesService.ts
  src/utils/Hydrator.ts
Labels: new thing

#25 add labels to projects
  dist/index.js
  dist/models/Operation.d.ts
  dist/models/Operation.js
  dist/models/Scheme.d.ts
  dist/models/Scheme.js
  dist/models/WorkOrder.d.ts
  dist/models/WorkOrder.js
  package.json
  src/models/Operation.ts
  src/models/Scheme.ts
  src/models/WorkOrder.ts
Labels: klto

#26 bump 0.1.108
  package.json
Labels: new thing

#27 remove statuses from projects
  dist/index.js
  dist/models/Operation.d.ts
  dist/models/Operation.js
  dist/models/Scheme.d.ts
  dist/models/Scheme.js
  dist/models/WorkOrder.d.ts
  dist/models/WorkOrder.js
  package.json
  src/models/Operation.ts
  src/models/Scheme.ts
  src/models/WorkOrder.ts
Labels: klto

#28 Move vehicle inspections to separate service, bump version
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/services/VehicleInspectionService.d.ts
  dist/services/VehicleInspectionService.js
  dist/services/VehiclesService.d.ts
  dist/services/VehiclesService.js
  package.json
  src/Client.ts
  src/services/VehicleInspectionService.ts
  src/services/VehiclesService.ts
Labels: improvement

#29 Update groups model
  dist/index.js
  dist/models/Group.d.ts
  dist/models/Group.js
  package.json
  src/models/Group.ts
Labels: new thing

#30 Update property model
  dist/index.js
  dist/models/Operation.js
  dist/models/Property.d.ts
  dist/models/Property.js
  dist/models/Street.d.ts
  dist/models/Street.js
  dist/services/PropertiesService.d.ts
  dist/services/PropertiesService.js
  dist/services/StreetsService.d.ts
  dist/services/StreetsService.js
  dist/utils/Hydrator.js
  package.json
  src/models/Operation.ts
  src/models/Property.ts
  src/models/Street.ts
  src/services/PropertiesService.ts
  src/services/StreetsService.ts
  src/utils/Hydrator.ts
Labels: improvement

#35 Customer interactions tweaks
  dist/Client.d.ts
  dist/Client.js
  dist/index.d.ts
  dist/index.js
  dist/models/Contact.d.ts
  dist/models/Contact.js
  dist/models/CustomerAccount.d.ts
  dist/models/CustomerAccount.js
  dist/models/CustomerInteraction.d.ts
  dist/models/CustomerInteraction.js
  dist/models/Operation.js
  dist/models/Property.js
  dist/services/ContactsService.d.ts
  dist/services/ContactsService.js
  dist/services/CustomerAccountsService.d.ts
  dist/services/CustomerAccountsService.js
  dist/services/CustomerInteractionsService.d.ts
  dist/services/CustomerInteractionsService.js
  dist/services/CustomersService.d.ts
  dist/services/CustomersService.js
  dist/utils/Hydrator.js
  dist/utils/JsonSerializer.d.ts
  dist/utils/JsonSerializer.js
  package.json
  src/Client.ts
  src/index.ts
  src/models/Contact.ts
  src/models/CustomerAccount.ts
  src/models/CustomerInteraction.ts
  src/models/Operation.ts
  src/models/Property.ts
  src/services/ContactsService.ts
  src/services/CustomerAccountsService.ts
  src/services/CustomerInteractionsService.ts
  src/services/CustomersService.ts
  src/utils/Hydrator.ts
  src/utils/JsonSerializer.ts
Labels: improvement

#36 update relationship payloads
  dist/Client.js
  dist/index.js
  dist/models/Operation.d.ts
  dist/services/BaseService.d.ts
  dist/utils/JsonSerializer.js
  dist/utils/Requests.js
  package.json
  src/models/Operation.ts
  src/services/AppointmentsService.ts
  src/utils/JsonSerializer.ts
Labels: klto

#37 add appointments
  dist/models/Appointment.d.ts
  dist/models/Appointment.js
  dist/services/AppointmentsService.d.ts
  dist/services/AppointmentsService.js
  package.json
  src/models/Appointment.ts
Labels: improvement

#39 Increase models test coverage
  dist/Client.d.ts
  dist/Client.js
  dist/index.js
  dist/models/CustomerAccount.d.ts
  dist/models/CustomerAccount.js
  dist/models/EquipmentCategory.js
  dist/models/EquipmentExposure.js
  dist/models/EquipmentManufacturer.js
  dist/utils/Hydrator.js
  dist/utils/JsonSerializer.d.ts
  dist/utils/JsonSerializer.js
  package.json
  src/models/EquipmentCategory.ts
  src/models/EquipmentExposure.ts
  src/models/EquipmentManufacturer.ts
  tests/models/Equipment.test.ts
  tests/models/EquipmentCategory.test.ts
  tests/models/EquipmentExposure.test.ts
  tests/models/EquipmentManufacturer.test.ts
  tests/utils/JsonSerializer/EquipmentAndEquipmentModel.test.ts
Labels: klto

#40 appointment fixes
  dist/index.d.ts
  dist/index.js
  dist/models/Appointment.d.ts
  dist/models/Appointment.js
  dist/utils/Hydrator.js
  src/index.ts
  src/models/Appointment.ts
  src/utils/Hydrator.ts
Labels: klto
